id: IE7CD78C8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T13:02:38+00:00'
last_modified: '2022-06-08T07:10:52.850445+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14746
  title: པདྨ་འོད་འབར་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C30F:
      image_group_id: I2PD18173
      title: ''
      total_pages: 172
      order: 1
      base_file: C30F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
